wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1634101242
    t:
      3:
      - 2
      4: 3.8.5
      5: 0.12.1
      8:
      - 1
      - 3
      - 5
